---
identifier: "CVE-2019-19275"
package_slug: "pypi/typed-ast"
title: "Out-of-bounds Read"
description: "typed_ast has an `ast_for_arguments` out-of-bounds read. An attacker
  with the ability to cause a Python interpreter to parse Python source (but not necessarily
  execute it) may be able to crash the interpreter process. This could be a concern,
  for example, in a web-based service that parses (but does not execute) Python code."
date: "2019-12-09"
pubdate: "2019-11-26"
affected_range: ">=1.3.0,<=1.3.1"
fixed_versions:
- "1.3.2"
affected_versions: "All versions starting from 1.3.0 up to 1.3.1"
not_impacted: "All versions before 1.3.0, all versions after 1.3.1"
solution: "Upgrade to version 1.3.2 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-19275"
- "https://bugs.python.org/issue36495"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "e754a77b-f90f-4249-9726-74a33f5bb768"
cwe_ids:
- "CWE-1035"
- "CWE-125"
- "CWE-937"
identifiers:
- "CVE-2019-19275"
