---
identifier: "CVE-2025-26699"
identifiers:
- "CVE-2025-26699"
- "GHSA-p3fp-8748-vqfq"
package_slug: "pypi/Django"
title: "Django vulnerable to Allocation of Resources Without Limits or Throttling"
description: "An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13,
  and 4.2 before 4.2.20. The django.utils.text.wrap() method and wordwrap template
  filter are subject to a potential denial-of-service attack when used with very long
  strings."
date: "2025-04-09"
pubdate: "2025-03-06"
affected_range: ">=4.2,<4.2.20||>=5.0,<5.0.13||>=5.1,<5.1.7"
fixed_versions:
- "4.2.20"
- "5.0.13"
- "5.1.7"
affected_versions: "All versions starting from 4.2 before 4.2.20, all versions starting
  from 5.0 before 5.0.13, all versions starting from 5.1 before 5.1.7"
not_impacted: "All versions before 4.2, all versions starting from 4.2.20 before 5.0,
  all versions starting from 5.0.13 before 5.1, all versions starting from 5.1.7"
solution: "Upgrade to versions 4.2.20, 5.0.13, 5.1.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2025-26699"
- "https://github.com/advisories/GHSA-p3fp-8748-vqfq"
- "https://docs.djangoproject.com/en/dev/releases/security"
- "https://github.com/django/django"
- "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2025-13.yaml"
- "https://groups.google.com/g/django-announce"
- "https://lists.debian.org/debian-lts-announce/2025/03/msg00012.html"
- "https://www.djangoproject.com/weblog/2025/mar/06/security-releases"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:L"
uuid: "a8c791a7-d4d8-423b-8197-86186ca108e6"
cwe_ids:
- "CWE-770"
- "CWE-937"
- "CWE-1035"
