---
identifier: "CVE-2024-39329"
identifiers:
- "CVE-2024-39329"
- "GHSA-x7q2-wr7g-xqmf"
package_slug: "pypi/Django"
title: "Django vulnerable to user enumeration attack"
description: "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14.
  The `django.contrib.auth.backends.ModelBackend.authenticate()` method allows remote
  attackers to enumerate users via a timing attack involving login requests for users
  with an unusable password."
date: "2024-07-10"
pubdate: "2024-07-10"
affected_range: ">=5.0,<5.0.7||>=4.2,<4.2.14"
fixed_versions:
- "5.0.7"
- "4.2.14"
affected_versions: "All versions starting from 4.2 before 4.2.14, all versions starting
  from 5.0 before 5.0.7"
not_impacted: "All versions before 4.2, all versions starting from 4.2.14 before 5.0,
  all versions starting from 5.0.7"
solution: "Upgrade to versions 4.2.14, 5.0.7 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2024-39329"
- "https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"
- "https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"
- "https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"
- "https://docs.djangoproject.com/en/dev/releases/security"
- "https://github.com/django/django"
- "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"
- "https://groups.google.com/forum/#%21forum/django-announce"
- "https://www.djangoproject.com/weblog/2024/jul/09/security-releases"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
uuid: "5575e088-fe41-43f1-b6e3-b4cb466a1e22"
cwe_ids:
- "CWE-208"
- "CWE-937"
- "CWE-1035"
