---
identifier: "CVE-2019-14235"
identifiers:
- "CVE-2019-14235"
- "GHSA-v9qg-3j8p-r63v"
package_slug: "pypi/Django"
title: "Uncontrolled Recursion in Django"
description: "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before
  2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri
  could lead to significant memory usage due to a recursion when repercent-encoding
  invalid UTF-8 octet sequences."
date: "2024-09-20"
pubdate: "2019-08-06"
affected_range: ">=1.11a1,<1.11.23||>=2.1a1,<2.1.11||>=2.2a1,<2.2.4"
fixed_versions:
- "1.11.23"
- "2.1.11"
- "2.2.4"
affected_versions: "All versions starting from 1.11a1 before 1.11.23, all versions
  starting from 2.1a1 before 2.1.11, all versions starting from 2.2a1 before 2.2.4"
not_impacted: "All versions before 1.11a1, all versions starting from 1.11.23 before
  2.1a1, all versions starting from 2.1.11 before 2.2a1, all versions starting from
  2.2.4"
solution: "Upgrade to versions 1.11.23, 2.1.11, 2.2.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-14235"
- "https://github.com/advisories/GHSA-v9qg-3j8p-r63v"
- "https://docs.djangoproject.com/en/dev/releases/security"
- "https://github.com/django/django"
- "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-14.yaml"
- "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK"
- "https://seclists.org/bugtraq/2019/Aug/15"
- "https://security.gentoo.org/glsa/202004-17"
- "https://security.netapp.com/advisory/ntap-20190828-0002"
- "https://www.debian.org/security/2019/dsa-4498"
- "https://www.djangoproject.com/weblog/2019/aug/01/security-releases"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "49afe3f9-e7ab-4d52-ad25-6e04bfdd670d"
cwe_ids:
- "CWE-674"
- "CWE-937"
- "CWE-1035"
