---
identifier: "CVE-2019-14235"
package_slug: "pypi/Django"
title: "Denial-of-service"
description: "If passed certain inputs, `django.utils.encoding.uri_to_iri` could lead
  to significant memory usage due to a recursion when repercent-encoding invalid UTF-8
  octet sequences."
date: "2019-08-12"
pubdate: "2019-08-02"
affected_range: ">=1.11,<1.11.23||>=2.1,<2.1.11||>=2.2,<2.2.4"
fixed_versions:
- "1.11.23"
- "2.1.11"
- "2.2.4"
affected_versions: "All versions starting from 1.11 before 1.11.23, all versions starting
  from 2.1 before 2.1.11, all versions starting from 2.2 before 2.2.4"
not_impacted: "All versions before 1.11, all versions starting from 1.11.23 before
  2.1, all versions starting from 2.1.11 before 2.2, all versions starting from 2.2.4"
solution: "Upgrade to versions 1.11.23, 2.1.11, 2.2.4 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2019-14235"
- "https://docs.djangoproject.com/en/dev/releases/security/"
- "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
credit: "MITRE"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "49afe3f9-e7ab-4d52-ad25-6e04bfdd670d"
cwe_ids:
- "CWE-1035"
- "CWE-674"
- "CWE-937"
identifiers:
- "CVE-2019-14235"
