---
identifier: "CVE-2014-0481"
identifiers:
- "GHSA-296w-6qhq-gf92"
- "CVE-2014-0481"
package_slug: "pypi/Django"
title: "Django denial of service via file upload naming"
description: "The default configuration for the file upload handling system in Django
  before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate
  3 uses a sequential file name generation process when a file with a conflicting
  name is uploaded, which allows remote attackers to cause a denial of service (CPU
  consumption) by unloading a multiple files with the same name."
date: "2023-08-15"
pubdate: "2022-05-14"
affected_range: "<1.4.14||>=1.5.0,<1.5.9||>=1.6,<1.6.6"
fixed_versions:
- "1.4.14"
- "1.5.9"
- "1.6.6"
affected_versions: "All versions before 1.4.14, all versions starting from 1.5.0 before
  1.5.9, all versions starting from 1.6 before 1.6.6"
not_impacted: "All versions starting from 1.4.14 before 1.5.0, all versions starting
  from 1.5.9 before 1.6, all versions starting from 1.6.6"
solution: "Upgrade to versions 1.4.14, 1.5.9, 1.6.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2014-0481"
- "https://www.djangoproject.com/weblog/2014/aug/20/security/"
- "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
- "http://www.debian.org/security/2014/dsa-3010"
- "https://github.com/django/django/commit/26cd48e166ac4d84317c8ee6d63ac52a87e8da99"
- "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41"
- "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1"
- "https://github.com/advisories/GHSA-296w-6qhq-gf92"
cvss_v2: "AV:N/AC:M/Au:N/C:N/I:N/A:P"
uuid: "4bf2d477-c2c6-4c69-8327-6811e57c1c2e"
cwe_ids:
- "CWE-1035"
- "CWE-399"
- "CWE-937"
