---
identifier: "CVE-2017-12600"
identifiers:
- "GHSA-fr58-2xhv-qp3w"
- "CVE-2017-12600"
package_slug: "pypi/opencv-python"
title: "Denial of Service in OpenCV"
description: "OpenCV (Open Source Computer Vision Library) has a denial of service
  (CPU consumption) issue, as demonstrated by the test case."
date: "2021-10-12"
pubdate: "2021-10-12"
affected_range: "<=3.3.0.9"
fixed_versions:
- "3.3.1.11"
affected_versions: "All versions up to 3.3.0.9"
not_impacted: "All versions after 3.3.0.9"
solution: "Upgrade to version 3.3.1.11 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2017-12600"
- "https://github.com/opencv/opencv/issues/9311"
- "https://github.com/opencv/opencv/pull/9376"
- "https://github.com/opencv/opencv-python/releases/tag/11"
- "https://github.com/opencv/opencv-python/releases/tag/9"
- "https://github.com/xiaoqx/pocs/blob/master/opencv.md"
- "https://security.gentoo.org/glsa/201712-02"
- "https://github.com/advisories/GHSA-fr58-2xhv-qp3w"
cvss_v2: "AV:N/AC:L/Au:N/C:N/I:N/A:C"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "474a292a-abdd-40f3-82f1-6c9a9c8c2a3c"
cwe_ids:
- "CWE-1035"
- "CWE-937"
