---
identifier: "CVE-2021-37661"
package_slug: "pypi/tensorflow"
title: "Incorrect Conversion between Numeric Types"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can cause a denial of service in `boosted_trees_create_quantile_stream_resource`
  by using negative arguments. The implementation does not validate that `num_streams`
  only contains non-negative numbers. In turn, this results in using this value to
  allocate memory. However, `reserve` receives an unsigned integer so there is an
  implicit conversion from a negative value to a large positive unsigned. This results
  in a crash from the standard library."
date: "2021-08-18"
pubdate: "2021-08-12"
affected_range: ">=2.3.0,<2.3.4||>=2.4.0,<2.4.3||>=2.5.0,<=2.6.0"
fixed_versions:
- "2.3.4"
- "2.4.3"
affected_versions: "All versions starting from 2.3.0 before 2.3.4, all versions starting
  from 2.4.0 before 2.4.3, all versions starting from 2.5.0 up to 2.6.0"
not_impacted: "All versions before 2.3.0, all versions starting from 2.3.4 before
  2.4.0, all versions starting from 2.4.3 before 2.5.0, all versions after 2.6.0"
solution: "Upgrade to versions 2.3.4, 2.4.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-37661"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "de9afdaf-8ee9-4dfd-a774-ac3bb1e3f724"
cwe_ids:
- "CWE-1035"
- "CWE-937"
identifiers:
- "CVE-2021-37661"
- "GHSA-gf88-j2mg-cc82"
