---
identifier: "CVE-2022-23565"
identifiers:
- "CVE-2022-23565"
- "GHSA-4v5p-v5h9-6xjx"
package_slug: "pypi/tensorflow"
title: "Reachable Assertion"
description: "Tensorflow is an Open Source Machine Learning Framework. An attacker
  can trigger denial of service via assertion failure by altering a `SavedModel` on
  disk such that `AttrDef`s of some operation are duplicated. The fix will be included
  in TensorFlow We will also cherrypick this commit on TensorFlow, TensorFlow, and
  TensorFlow, as these are also affected and still in supported range."
date: "2022-02-09"
pubdate: "2022-02-04"
affected_range: "<=2.5.2||>=2.6.0,<=2.6.2||==2.7.0"
fixed_versions:
- "2.5.3"
- "2.6.3"
- "2.7.1"
affected_versions: "All versions up to 2.5.2, all versions starting from 2.6.0 up
  to 2.6.2, version 2.7.0"
not_impacted: "All versions after 2.5.2 before 2.6.0, all versions after 2.6.2 before
  2.7.0, all versions after 2.7.0"
solution: "Upgrade to versions 2.5.3, 2.6.3, 2.7.1 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2022-23565"
- "https://github.com/tensorflow/tensorflow/commit/c2b31ff2d3151acb230edc3f5b1832d2c713a9e0"
- "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-4v5p-v5h9-6xjx"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "fd6787e1-48b6-45a7-87c9-06e309b84349"
cwe_ids:
- "CWE-1035"
- "CWE-617"
- "CWE-937"
