---
identifier: "CVE-2021-25287"
identifiers:
- "CVE-2021-25287"
- "GHSA-77gc-v2xv-rvvh"
package_slug: "pypi/Pillow"
title: "Out-of-bounds Read in Pillow"
description: "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds
  read in J2kDecode, in j2ku_graya_la."
date: "2024-10-09"
pubdate: "2021-06-08"
affected_range: ">=2.4.0,<8.2.0"
fixed_versions:
- "8.2.0"
affected_versions: "All versions starting from 2.4.0 before 8.2.0"
not_impacted: "All versions before 2.4.0, all versions starting from 8.2.0"
solution: "Upgrade to version 8.2.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-25287"
- "https://github.com/advisories/GHSA-77gc-v2xv-rvvh"
- "https://github.com/python-pillow/Pillow/pull/5377#issuecomment-833821470"
- "https://github.com/python-pillow/Pillow/pull/5377/commits/3bf5eddb89afdf690eceaa52bc4d3546ba9a5f87"
- "https://github.com/python-pillow/Pillow/commit/3bf5eddb89afdf690eceaa52bc4d3546ba9a5f87"
- "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2021-137.yaml"
- "https://github.com/python-pillow/Pillow"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL"
- "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve-2021-25288-fix-oob-read-in-jpeg2kdecode"
- "https://security.gentoo.org/glsa/202107-33"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
uuid: "28b7755e-d70f-4dbc-ab71-454977183cc7"
cwe_ids:
- "CWE-125"
- "CWE-937"
- "CWE-1035"
