---
identifier: "CVE-2024-1141"
identifiers:
- "GHSA-wgpq-p2hm-56v9"
- "CVE-2024-1141"
package_slug: "pypi/glance-store"
title: "Logging of Excessive Data"
description: "A vulnerability was found in python-glance-store. The issue occurs when
  the package logs the access_key for the glance-store when the DEBUG log level is
  enabled."
date: "2024-02-05"
pubdate: "2024-02-01"
affected_range: "<=4.6.1"
fixed_versions: []
affected_versions: "All versions up to 4.6.1"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2024-1141"
- "https://access.redhat.com/security/cve/CVE-2024-1141"
- "https://bugzilla.redhat.com/show_bug.cgi?id=2258836"
- "https://github.com/openstack/glance_store/commit/d6e531af4821c8466b1e9404f12f89f6216417f2"
- "https://github.com/advisories/GHSA-wgpq-p2hm-56v9"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "7cfc50fa-a430-4e56-9a10-ed1044d7b8fc"
cwe_ids:
- "CWE-1035"
- "CWE-779"
- "CWE-937"
