---
identifier: "CVE-2021-21394"
identifiers:
- "CVE-2021-21394"
- "GHSA-w9fg-xffh-p362"
package_slug: "pypi/matrix-synapse"
title: "Denial of service (via resource exhaustion) due to improper input validation
  on third-party identifier endpoints"
description: "Missing input validation of some parameters on the endpoints used to
  confirm third-party identifiers could cause excessive use of disk space and memory
  leading to resource exhaustion."
date: "2024-09-24"
pubdate: "2021-04-13"
affected_range: "<1.28.0"
fixed_versions:
- "1.28.0"
affected_versions: "All versions before 1.28.0"
not_impacted: "All versions starting from 1.28.0"
solution: "Upgrade to version 1.28.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-21394"
- "https://github.com/advisories/GHSA-w9fg-xffh-p362"
- "https://github.com/matrix-org/synapse/security/advisories/GHSA-w9fg-xffh-p362"
- "https://github.com/matrix-org/synapse/pull/9321"
- "https://github.com/matrix-org/synapse/pull/9393"
- "https://github.com/matrix-org/synapse"
- "https://github.com/pypa/advisory-database/tree/main/vulns/matrix-synapse/PYSEC-2021-27.yaml"
- "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TNNAJOZNMVMXM6AS7RFFKB4QLUJ4IFEY"
- "https://pypi.org/project/matrix-synapse"
cvss_v2: "AV:N/AC:L/Au:S/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "f0f61509-341a-4190-b6eb-e4014af575c4"
cwe_ids:
- "CWE-20"
- "CWE-937"
- "CWE-1035"
