---
identifier: "CVE-2022-40899"
identifiers:
- "CVE-2022-40899"
package_slug: "pypi/future"
title: "Denial of Service"
description: "An issue discovered in Python Charmers Future 0.18.2 and earlier allows
  remote attackers to cause a denial of service via crafted Set-Cookie header from
  malicious web server."
date: "2023-01-23"
pubdate: "2022-12-23"
affected_range: "<=0.18.2"
fixed_versions:
- "0.18.3"
affected_versions: "All versions up to 0.18.2"
not_impacted: "All versions after 0.18.2"
solution: "Upgrade to version 0.18.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2022-40899"
- "https://pypi.org/project/future/"
- "https://github.com/python/cpython/pull/17157"
- "https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215"
- "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "59f72dd3-88c1-47e8-9757-2e68086121cf"
cwe_ids:
- "CWE-1035"
- "CWE-937"
