---
identifier: "CVE-2018-7206"
package_slug: "pypi/oauthenticator"
title: "Improper Access Control"
description: "An issue was discovered in Project Jupyter JupyterHub OAuthenticator.
  When using JupyterHub with a GitLab allowlist for access control, group membership
  is not checked correctly, allowing members that are not in the allowlist to create
  accounts on the Hub."
date: "2019-10-03"
pubdate: "2018-02-18"
affected_range: ">=0.6.0,<=0.6.1||>=0.7.0,<=0.7.2"
fixed_versions:
- "0.6.2"
- "0.7.3"
affected_versions: "All versions starting from 0.6.0 up to 0.6.1, all versions starting
  from 0.7.0 up to 0.7.2"
not_impacted: "All versions before 0.6.0, all versions after 0.6.1 before 0.7.0, all
  versions after 0.7.2"
solution: "Upgrade to versions 0.6.2, 0.7.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-7206"
- "https://github.com/jupyterhub/oauthenticator/blob/8499dc2/CHANGELOG.md#073---2018-02-16"
cvss_v2: "AV:N/AC:L/Au:S/C:P/I:P/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "7f4d0784-970e-4d5d-bcd5-8464aea52e08"
cwe_ids:
- "CWE-1035"
- "CWE-937"
